### ISSUE TITLE
Actions Report Error of assigning a constant variable

### ISSUE THREAD

**Issue by wshen001** [wyugen/shopify-theme-action#3]
```
TypeError: Assignment to constant variable.
    at main (/home/runner/work/_actions/wyugen/shopify-theme-action/v0.3/dist/index.js:4560:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I have tried to integrate the action but it got this error... could you give me some advice?

**Comment by wshen001** [comment]
the issue disappeared after re-run.
